name: Google Java Format

on:
  push:
    branches: [ master ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Google Java Format Job

    # GitHub token permissions
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Download Google Java Format
        run: |
          curl -L -o google-java-format.jar \
            https://github.com/google/google-java-format/releases/download/v1.33.0/google-java-format-1.33.0-all-deps.jar

      - name: Format each Java file individually
        run: |
          shopt -s globstar
          for f in **/*.java; do
            if [[ "$f" == *module-info.java ]]; then
              continue
            fi
            echo "Formatting $f"
            java -jar google-java-format.jar --replace "$f"
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "Apply Google Java Format"
